import type { GalleryItem, Review, SiteStats } from "./types";

export const seedGallery: GalleryItem[] = [
  {
    id: "g-wedding",
    type: "photo",
    title: "Sharma × Kapoor Wedding",
    category: "Weddings & Events",
    src: "/images/gallery/wedding.jpg",
    visible: true,
    featured: true,
    order: 1,
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "g-portrait",
    type: "photo",
    title: "Neon Editorial Series",
    category: "Portraits",
    src: "/images/gallery/portrait.jpg",
    visible: true,
    featured: true,
    order: 2,
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "g-perfume",
    type: "photo",
    title: "Aura — Fragrance Campaign",
    category: "Product",
    src: "/images/gallery/product-perfume.jpg",
    visible: true,
    featured: true,
    order: 3,
    createdAt: "2026-01-08T10:00:00.000Z",
  },
  {
    id: "g-sneaker",
    type: "photo",
    title: "Velocity Drop Campaign",
    category: "Product",
    src: "/images/gallery/product-sneaker.jpg",
    visible: true,
    order: 4,
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: "g-event",
    type: "photo",
    title: "Aarav's 25th Birthday Bash",
    category: "Weddings & Events",
    src: "/images/gallery/event.jpg",
    visible: true,
    order: 5,
    createdAt: "2025-12-28T10:00:00.000Z",
  },
  {
    id: "g-bts",
    type: "photo",
    title: "On Set — “Midnight Run”",
    category: "Behind The Scenes",
    src: "/images/gallery/bts.jpg",
    visible: true,
    order: 6,
    createdAt: "2025-12-20T10:00:00.000Z",
  },
  {
    id: "g-food",
    type: "photo",
    title: "The Salt Room — Menu Shoot",
    category: "Food & Hospitality",
    src: "/images/gallery/food.jpg",
    visible: true,
    order: 7,
    createdAt: "2025-12-15T10:00:00.000Z",
  },
  {
    id: "g-brand",
    type: "photo",
    title: "CityPulse Audio Campaign",
    category: "Brand Campaigns",
    src: "/images/gallery/brand.jpg",
    visible: true,
    order: 8,
    createdAt: "2025-12-10T10:00:00.000Z",
  },
  {
    id: "g-reel-1",
    type: "reel",
    title: "Studio Motion Reel",
    category: "Reels",
    src: "/images/gallery/reel-dance.jpg",
    views: "48.2K",
    duration: "0:24",
    visible: true,
    order: 9,
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "g-reel-2",
    type: "reel",
    title: "Kitchen Fire Reel",
    category: "Reels",
    src: "/images/gallery/reel-cooking.jpg",
    views: "31.7K",
    duration: "0:31",
    visible: true,
    order: 10,
    createdAt: "2026-01-06T10:00:00.000Z",
  },
  {
    id: "g-reel-3",
    type: "reel",
    title: "Street Frames Reel",
    category: "Reels",
    src: "/images/gallery/reel-fashion.jpg",
    views: "22.4K",
    duration: "0:18",
    visible: true,
    order: 11,
    createdAt: "2025-12-22T10:00:00.000Z",
  },
];

export const seedReviews: Review[] = [
  {
    id: "rv-1",
    name: "Priya Malhotra",
    rating: 5,
    text: "Booked the monthly Standard package for my boutique. Reels quality is unreal and we gained 3k followers in the first month. The team plans everything — I just show up!",
    service: "Monthly Growth",
    date: "2026-01-18T09:00:00.000Z",
    visible: true,
  },
  {
    id: "rv-2",
    name: "Rahul Verma",
    rating: 5,
    text: "They covered my sister's birthday with the ₹5,000 package. Unlimited photos plus an edited reel that honestly looked like a movie trailer. Worth every rupee.",
    service: "Events",
    date: "2026-01-11T09:00:00.000Z",
    visible: true,
  },
  {
    id: "rv-3",
    name: "Sneha Iyer",
    rating: 5,
    text: "Our café's product shots doubled online orders in two weeks. Moody, premium, exactly the vibe we asked for. Communication was crisp throughout.",
    service: "Product Photography",
    date: "2025-12-30T09:00:00.000Z",
    visible: true,
  },
  {
    id: "rv-4",
    name: "Arjun Mehta",
    rating: 4,
    text: "Premium reels for my fitness page — great hooks and editing. Slight delay on one delivery but they made up for it with a bonus reel. Recommended.",
    service: "Reels Shoot",
    date: "2025-12-19T09:00:00.000Z",
    visible: true,
  },
  {
    id: "rv-5",
    name: "Kavitha Reddy",
    rating: 5,
    text: "The growth meetings alone are worth the Premium package. Analytics, content calendar, everything handled. Finally social media feels like an asset, not a chore.",
    service: "Premium Growth",
    date: "2025-12-08T09:00:00.000Z",
    visible: true,
  },
  {
    id: "rv-6",
    name: "Vikram Singh Rathore",
    rating: 5,
    text: "Shot our anniversary — candid moments captured beautifully, album delivered in 48 hours. True professionals with top-tier gear.",
    service: "Photography",
    date: "2025-11-26T09:00:00.000Z",
    visible: true,
  },
];

export const seedStats: SiteStats = {
  instagramFollowers: 12840,
  followersToday: 36,
  projectsDelivered: 320,
  happyClients: 145,
  reelsProduced: 900,
  updatedAt: "2026-08-01T00:00:00.000Z",
};
